# Generated by Django 2.2 on 2019-04-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('clientType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('modelNum', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('celltechnology', models.CharField(blank=True, max_length=200)),
                ('cellmanufacture', models.CharField(blank=True, max_length=50, null=True)),
                ('numberofcells', models.CharField(blank=True, max_length=50)),
                ('numberofcellsinseries', models.CharField(blank=True, max_length=50)),
                ('numberofseriesinstrings', models.CharField(blank=True, max_length=50)),
                ('numberofdiodes', models.CharField(blank=True, max_length=50)),
                ('productlength', models.CharField(blank=True, max_length=50)),
                ('productwidth', models.CharField(blank=True, max_length=50)),
                ('productweight', models.CharField(blank=True, max_length=50)),
                ('superstratetype', models.CharField(blank=True, max_length=50)),
                ('superstratemanufacturer', models.CharField(blank=True, max_length=50)),
                ('substratetype', models.CharField(blank=True, max_length=50)),
                ('substratemanufacturer', models.CharField(blank=True, max_length=50)),
                ('frametype', models.CharField(blank=True, max_length=50)),
                ('frameadhesive', models.CharField(blank=True, max_length=50)),
                ('encapsulanttype', models.CharField(blank=True, max_length=50)),
                ('encapsulantmanufacturer', models.CharField(blank=True, max_length=50)),
                ('junctionboxtype', models.CharField(blank=True, max_length=50)),
                ('junctionboxmanufacturer', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('sequenceID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sequencename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('standardID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('standardName', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=400)),
                ('publisheddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('officephone', models.CharField(blank=True, max_length=15)),
                ('cellphone', models.CharField(blank=True, max_length=100)),
                ('prefix', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss')], max_length=8)),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('isFIrequired', models.CharField(max_length=50)),
                ('FIfrequency', models.CharField(max_length=50)),
                ('standardID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsystemvoltage', models.CharField(blank=True, max_length=50)),
                ('opencircuitvoltage', models.CharField(blank=True, max_length=50)),
                ('shortcircuitcurrent', models.CharField(blank=True, max_length=50)),
                ('voltageatmaxpower', models.CharField(blank=True, max_length=50)),
                ('currentatmaxpower', models.CharField(blank=True, max_length=50)),
                ('maxpoweroutput', models.CharField(blank=True, max_length=50)),
                ('fillfactor', models.CharField(blank=True, max_length=50)),
                ('modelNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.Product')),
                ('sequenceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.TestSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address1', models.TextField(max_length=200)),
                ('address2', models.TextField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(blank=True, max_length=15)),
                ('faxnumber', models.CharField(blank=True, max_length=15)),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificateID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('certnumber', models.CharField(max_length=50)),
                ('reportnumber', models.CharField(max_length=50)),
                ('issuedate', models.CharField(blank=True, max_length=50, null=True)),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.Location')),
                ('modelNum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.Product')),
                ('standardID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.TestStandard')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SolarPV.User')),
            ],
        ),
    ]
