# Generated by Django 2.2 on 2019-04-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefix',
            field=models.CharField(choices=[('Dr.', 'Dr. description'), ('Mr.', 'Mr description'), ('Mrs.', 'Mrs description'), ('Miss', 'Miss descripion')], max_length=8),
        ),
    ]
